### ISSUE TITLE
Abnormal behavior when added scroll view over it.

### ISSUE THREAD

**Issue by shahwaiz90** [yingLanNull/CircleAlarmTimerView#2]
I've embedded it in my app, the page where it is embedded in, needs to be scrolled down. So when I added a scroll view in the page it affects the working of it. Most of the time it doesn't let me drag its button down and when some times it goes down it releases it self randomly. Total abnormal behavior in ScrollView.

**Comment by yingLanNull** [comment]
Sorry, I have not yet adapted to scrollview @shahwaiz90

**Comment by shahwaiz90** [comment]
I've fixed the issue. Updated the code there, please accept the proposed modifications.
